all:
	mkdir -p ../bin
	gcc -Wall -std=gnu99 -o ../bin/mosp-friendly friendly.c
	gcc -Wall -std=gnu99 -o ../bin/mosp-exit exit.c
	gcc -Wall -std=gnu99 -o ../bin/mosp-forever forever.c
	gcc -Wall -std=gnu99 -o ../bin/mosp-2020 2020.c
	gcc -Wall -std=gnu99 -o ../bin/mosp-nanana nanana.c
	gcc -Wall -std=gnu99 -o ../bin/mosp-segway segway.c
